# Generated by Django 3.2.25 on 2025-07-24 05:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=15)),
                ('moneda', models.CharField(default='COP', max_length=5)),
                ('PAN_1', models.DecimalField(decimal_places=0, max_digits=4)),
                ('PAN_2', models.DecimalField(decimal_places=0, max_digits=4)),
                ('PAN_3', models.DecimalField(decimal_places=0, max_digits=4)),
                ('PAN_4', models.DecimalField(decimal_places=0, max_digits=4)),
                ('EXP_M', models.DecimalField(decimal_places=0, max_digits=2)),
                ('EXP_Y', models.DecimalField(decimal_places=0, max_digits=2)),
                ('CVS', models.DecimalField(decimal_places=0, max_digits=3)),
                ('titular', models.CharField(max_length=100)),
                ('ultimos_4_digitos', models.CharField(max_length=4)),
                ('marca_tarjeta', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion', models.CharField(max_length=255)),
                ('ciudad', models.CharField(max_length=100)),
                ('departamento', models.CharField(max_length=100)),
                ('codigo_postal', models.CharField(max_length=20)),
                ('pais', models.CharField(default='Colombia', max_length=255)),
                ('id_transaccion_externa', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(default='pendiete', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
