# Generated by Django 3.2.25 on 2025-07-24 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transacciones', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaccion',
            name='usuario',
        ),
    ]
