# Generated by Django 3.2.25 on 2025-07-25 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacciones', '0002_remove_transaccion_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccion',
            name='EXP_M',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='EXP_Y',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='PAN_1',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='PAN_2',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='PAN_3',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='PAN_4',
            field=models.CharField(max_length=4),
        ),
    ]
