# Generated by Django 3.2.25 on 2025-07-27 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacciones', '0004_alter_transaccion_monto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccion',
            name='CVS',
            field=models.CharField(max_length=3),
        ),
    ]
