# Generated by Django 3.2.25 on 2025-07-27 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacciones', '0005_alter_transaccion_cvs'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='total_pagado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
